# Generated by Django 4.1.1 on 2022-09-14 00:46

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fh_creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('de_mail', models.EmailField(max_length=254)),
                ('de_cel', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
            ],
        ),
    ]
