# Generated by Django 4.1.1 on 2022-09-30 20:31

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('paweb', '0002_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fh_creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('de_quien', models.CharField(max_length=40, verbose_name='de_quien')),
                ('texto', models.TextField(max_length=300, verbose_name='texto')),
            ],
            options={
                'verbose_name_plural': 'Testimonios',
            },
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='mensajecontacto',
            options={'verbose_name_plural': 'MensajesContacto'},
        ),
        migrations.AlterField(
            model_name='mensajecontacto',
            name='de_cel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='mensajecontacto',
            name='de_mail',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='mensajecontacto',
            name='texto',
            field=models.TextField(verbose_name='mensaje'),
        ),
        migrations.AlterField(
            model_name='mensajecontacto',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='asunto'),
        ),
    ]
