# Generated by Django 4.1.1 on 2022-10-05 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paweb', '0003_testimonio_alter_actividad_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fh_creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('de_quien', models.CharField(max_length=40, verbose_name='de_quien')),
                ('texto', models.TextField(max_length=300, verbose_name='texto')),
                ('categorias', models.CharField(max_length=200, verbose_name='categorias')),
            ],
            options={
                'verbose_name_plural': 'Avisos',
            },
        ),
    ]
