# Generated by Django 4.1.1 on 2022-10-07 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paweb', '0004_aviso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fh_creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('de_quien', models.CharField(max_length=40, verbose_name='de_quien')),
                ('a_quien', models.CharField(max_length=40, verbose_name='a_quien')),
                ('por', models.CharField(max_length=200, verbose_name='por')),
                ('cuanto', models.IntegerField(verbose_name='cuanto')),
            ],
            options={
                'verbose_name_plural': 'Transacciones',
            },
        ),
    ]
