# Generated by Django 4.1.1 on 2022-10-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paweb', '0005_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='titulo',
            field=models.CharField(default='completar titulo', max_length=40, verbose_name='titulo'),
            preserve_default=False,
        ),
    ]
