# Generated by Django 4.1.1 on 2022-10-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paweb', '0006_aviso_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='cuanto',
            field=models.IntegerField(default=0, verbose_name='cuanto'),
            preserve_default=False,
        ),
    ]
