# Generated by Django 4.1.1 on 2022-10-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paweb', '0007_aviso_cuanto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
